import "./globals.css";
import Navbar from "./components/Navbar";
import SideBarNav from "./components/SidebarNav";


export const metadata = {
  title: "EBC APP",
  description: "Generated by create next app",
  manifest:"/manifest.json",
  icons: {

    apple:"/icon.png"

  },
  themecolor:"#181c32"
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <SideBarNav />
        {children}
        </body>
    </html>
  );
}
