import "./globals.css";
import Navbar from "./components/Navbar";
import SideBarNav from "./components/SidebarNav";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <SideBarNav />
        {children}
        </body>
    </html>
  );
}
